# Generated by Django 3.0.4 on 2020-03-23 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('user', models.IntegerField()),
                ('week_number', models.IntegerField()),
                ('text', models.TextField(blank=True)),
            ],
        ),
    ]
