# Generated by Django 3.0.4 on 2020-03-24 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('week', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='week',
            old_name='user',
            new_name='user_id',
        ),
        migrations.AddField(
            model_name='week',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
