# Generated by Django 3.0.4 on 2020-03-24 23:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('week', '0004_auto_20200324_2233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='week',
            name='notes',
        ),
        migrations.AddField(
            model_name='note',
            name='week',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='week.Week'),
        ),
    ]
