# Generated by Django 3.0.4 on 2020-03-24 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('week', '0005_auto_20200324_2331'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='week',
            new_name='week_id',
        ),
    ]
