# Generated by Django 3.0.4 on 2020-03-24 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('week', '0006_auto_20200324_2347'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='week_id',
            new_name='week',
        ),
    ]
